// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANPSJWxMXkhkZ6l0pnHf3IGVbLxL_tRxY',
    appId: '1:629516758924:ios:d6bd5b639e4d02a90870a9',
    messagingSenderId: '629516758924',
    projectId: 'gigmate-cffa5',
    storageBucket: 'gigmate-cffa5.firebasestorage.app',
    iosBundleId: 'com.gigmate.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANPSJWxMXkhkZ6l0pnHf3IGVbLxL_tRxY',
    appId: '1:629516758924:ios:aabcbbb7a013768c0870a9',
    messagingSenderId: '629516758924',
    projectId: 'gigmate-cffa5',
    storageBucket: 'gigmate-cffa5.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFnOaG9W1QB096dZkBIU3JLzgAXqAUM-8',
    appId: '1:629516758924:web:fcbad21c9cc4ad8f0870a9',
    messagingSenderId: '629516758924',
    projectId: 'gigmate-cffa5',
    authDomain: 'gigmate-cffa5.firebaseapp.com',
    storageBucket: 'gigmate-cffa5.firebasestorage.app',
    measurementId: 'G-NE4LXN3JBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC07xdPyGVIQBF2I4fPAtYeaXV5TNX9q58',
    appId: '1:629516758924:android:c95e0dfa4a195ae50870a9',
    messagingSenderId: '629516758924',
    projectId: 'gigmate-cffa5',
    storageBucket: 'gigmate-cffa5.firebasestorage.app',
  );

}